[project]
name = "workmate-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.4.1",
    "tabulate>=0.9.0",
]

[tool.pytest.ini_options]
pythonpath = ['src']
